version: "3.9"

services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage

  app:
    build: .
    container_name: rag-app

    depends_on:
      - ollama
      - qdrant

    ports:
      - "8080:8080"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui

    depends_on:
      - ollama

    environment:
      OLLAMA_BASE_URL: http://ollama:11434

    ports:
      - "3000:8080"

volumes:
  ollama:
  qdrant-data: